<?php

/**
 * @file edit_limit.module
 * Primary module file for Edit Limit. This contains all the hooks needed to
 * run the module.
 */

use Drupal\comment\CommentInterface;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

define('EDIT_LIMIT_NODE_COUNT_DEFAULT', 3);
define('EDIT_LIMIT_COMMENT_COUNT', 3);
define('EDIT_LIMIT_NODE_TIME_DEFAULT', 86400); // in seconds, 1 day
define('EDIT_LIMIT_COMMENT_TIME', 300); // in seconds, 5 minutes
define('EDIT_LIMIT_TIME_UNITS', '@seconds,@minutes,@hours,@days');
define('EDIT_LIMIT_TIME_UNIT_DEFAULT', 'seconds');

/**
 * Implements hook_menu_alter().
 *
 * This allows additional checks to be made for granting access checks. For instance,
 * the node menu items use node_access() to grant permissions to edit nodes, but we
 * want to not only check that, but also check to see if the user is allowed to continue
 * making edits.
 */
function edit_limit_menu_alter(&$items) {
  // Override comment edit access checks
  $items['comment/%comment/edit']['access callback'] = 'edit_limit_comment_access';
}

/**
 * Implements hook_node_access().
 */
function edit_limit_node_access(NodeInterface $node, $op, AccountInterface $account) {
  if ($op == 'update') {

    if ($account->hasPermission('bypass edit limits')) {
      return AccessResult::neutral();
    }

    return _edit_limit_user_access($node);
  }

  return AccessResult::neutral();
}

/**
 * Helper function to perform additional access checks after node_access() has
 * been checked.
 */
function _edit_limit_user_access(NodeInterface $node) {
  // Be liberal here. The user has already passed node_access() by this point.
  $return = AccessResult::neutral();

  // If this is a new node, let it go.
  if ($node->isNew()) {
    return $return;
  }

  // Get config.
  $config = \Drupal::config('edit_limit.settings');

  // Only limit edits if the content type is in the list.
  $allowed_types = $config->get('node_types');
  if (empty($allowed_types[$node->bundle()])) {
    return $return;
  }

  // Get the time limit settings
  $edit_limit_node_time_enabled = $config->get('node_time_enabled');
  $time_limits['default'] = intval($config->get('node_time_default')) * 24 * 60 * 60;
  $time_limits['node'][$node->bundle()] = $time_limits['default'];

  // Get the edit count limit settings.
  $edit_limit_node_count_enabled = $config->get('node_count_enabled');
  $count_limits['default'] = intval($config->get('node_count_default'));
  $count_limits['node'][$node->bundle()] = $count_limits['default'];

  // If no options are enabled, we're done.
  if (!$edit_limit_node_time_enabled && !$edit_limit_node_count_enabled) {
    return $return;
  }

  // Test that the node hasn't been edited more than the allowed number of times.
  $count_limit_reached = FALSE;
  if ($edit_limit_node_count_enabled && $return) {
    $edit_count = edit_limit_node_count($node->id());

    $count_limit = ($count_limits['node'][$node->bundle()]) ? $count_limits['node'][$node->bundle()] : $count_limits['node']['default'];
    if ($count_limit <= $edit_count) {
      $return = FALSE;
      $count_limit_reached = TRUE;
    }
  }

  // Test that the node was not created longer ago than the allowed time limit.
  if ($edit_limit_node_time_enabled && $return) {
    $time_unit = $config->get('node_time_unit');
    $timeleft = intval($node->getCreatedTime()) + intval(_unit_to_seconds($config->get('node_time_default'), $time_unit)) - REQUEST_TIME;

    if ($timeleft <= 0) {
      $return = AccessResult::forbidden();
    }
    elseif (!$count_limit_reached && \Drupal::routeMatch()->getRouteName() == 'entity.node.edit_form') {
      static $type;
      if (empty($type)) {
        $type = 'status';
        $message = '<span class="edit-limit-time-unit-' . $time_unit . '">' . t('You have %seconds %time_unit left to edit this content.', array('%seconds' => $timeleft, '%time_unit' => t('seconds'))) . '</span>';
        drupal_set_message(['#markup' => $message, '#attached' => ['library' => ['js' => 'edit_limit/edit_limit.countdown']]], $type);
      }
    }
  }

  return $return;
}

/**
 * Helper function to convert a time unit to seconds
 *
 * @param int $time
 * @param string $unit
 *
 * @return int
 */
function _unit_to_seconds($time = 0, $unit = 'seconds') {
  switch ($unit) {
    case 'minutes':
      $time_in_seconds = $time * 60;
      break;
    case 'hours':
      $time_in_seconds = $time * 60 * 60;
      break;
    case 'days':
      $time_in_seconds = $time * 60 * 60 * 24;
      break;
    default:
      $time_in_seconds = $time;
      break;
  }
  return $time_in_seconds;
}

/**
 * Implements hook_comment_access().
 */
function edit_limit_comment_access(CommentInterface $entity, $operation, AccountInterface $account) {
  if ($account->hasPermission('post comments') && $operation == 'update') {

    $return = AccessResult::neutral();

    if ($account->hasPermission('bypass edit limits')) {
      return $return;
    }

    // Get config.
    $config = \Drupal::config('edit_limit.settings');

    // Only limit edits if content type is in the list.
    $node = $entity->getCommentedEntity();
    // Only limit edits if the content type is in the list.
    $allowed_types = $config->get('comment_types');
    if (empty($allowed_types[$node->bundle()])) {
      return $return;
    }

    if ($config->get('comment_time_enabled')) {
      $time_unit = $config->get('comment_time_unit');
      // By this point, we want to return false if the time has passed.
      if ($entity->getCreatedTime() + intval(_unit_to_seconds($config->get('comment_time'), $time_unit)) < REQUEST_TIME) {
        $return = AccessResult::forbidden();
      }
      else {
        static $time_left;
        if (empty($time_left) && $account->hasPermission('edit own comments') && \Drupal::routeMatch()->getRouteName() == 'entity.comment.edit_form') {
          $time_left = $entity->getCreatedTime() + intval(_unit_to_seconds($config->get('comment_time'), $time_unit)) - REQUEST_TIME;
          $type = 'status';
          $message = '<span class="edit-limit-time-unit-' . $time_unit . '">' . t('You have %time_left %time_unit left to edit this comment.', array('%time_left' => $time_left, '%time_unit' => 'seconds')) . '</span>';
          drupal_set_message(['#markup' => $message, '#attached' => ['library' => ['js' => 'edit_limit/edit_limit.countdown']]], $type);
        }
      }
    }

    return $return;
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_node_update().
 */
function edit_limit_node_update(NodeInterface $node) {
  if (\Drupal::config('edit_limit.settings')->get('node_count_enabled')) {
    // Update the count of edit limits.
    $count_data = db_select('edit_limit_node_count', 'e')
      ->fields('e')
      ->condition('nid', $node->id(), '=')
      ->execute()
      ->fetchAssoc();

    $edit_count = 0;
    if (!empty($count_data)) {
      $edit_count = $count_data['count'];
    }
    $edit_count++;
    db_merge('edit_limit_node_counts')
      ->key('nid', $node->id())
      ->fields(['nid', 'count'], [$node->id(), $edit_count])
      ->execute();
  }
}

/**
 * Implements hook_entity_prepare_form().
 */
function edit_limit_entity_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  if ($entity->getEntityTypeId() == 'node' && !$entity->isNew()) {
    if (\Drupal::config('edit_limit')->get('node_count_enabled')) {
      $limit = \Drupal::config('edit_limit')->get('node_count_default');
      $count = edit_limit_node_count($entity->id());

      // If the edit count is getting close to the limit, make this a warning instead of a simple status
      $type = ($count + 2 > $limit) ? 'warning' : 'status';
      $message = t("This node has been edit @count out of @limit times, after which it will be locked.", array('@count' => $count, '@limit' => $limit));
      drupal_set_message($message, $type);
    }
  }
}

/**
 * Helper function to get the number of times a particular node
 * has been edited.
 *
 * @param int $nid
 *   The node nid
 *
 * @return int $count
 */
function edit_limit_node_count($nid) {
  $count = db_select('edit_limit_node_count', 'e')
    ->fields('e', array('count'))
    ->condition('nid', $nid, '=')
    ->execute()
    ->fetchField();
  $count = (empty($count)) ? 0 : $count;
  return $count;
}
